In [15]:
# import pandas 
import pandas as pd

# import dataset
df = pd.read_csv(r"C:\Users\Nadia\Desktop\UNI\3179\current sem\Assignment 2\Natural Disasters Datasets\not cleaned yet\earthquake_dataset.csv")

df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2022-10-13T02:06:45.547Z,62.258000,-149.688400,50.400000,2.20,ml,NaN,NaN,NaN,0.24000,...,2022-10-13T02:07:59.370Z,"13 km NE of Susitna North, Alaska",earthquake,NaN,1.000000,NaN,NaN,automatic,ak,ak
1,2022-10-13T01:53:35.883Z,35.951187,-97.873871,4.408605,2.17,ml,39.0,47.116041,0.092802,0.37182,...,2022-10-13T01:56:59.040Z,"4 km SE of Dover, Oklahoma",earthquake,1.821092,1.749625,NaN,31.0,automatic,ok,ok
2,2022-10-13T01:47:00.530Z,38.803001,-122.761169,0.570000,0.36,md,7.0,167.000000,0.002632,0.03000,...,2022-10-13T01:48:35.735Z,"3km N of The Geysers, CA",earthquake,0.560000,0.470000,NaN,1.0,automatic,nc,nc
3,2022-10-13T01:44:25.890Z,19.150667,-155.503174,33.330002,2.53,md,43.0,140.000000,NaN,0.12000,...,2022-10-13T02:05:07.625Z,"6 km SSW of Pāhala, Hawaii",earthquake,0.640000,0.760000,1.2,28.0,automatic,hv,hv
4,2022-10-13T01:41:24.537Z,64.795600,-151.394300,13.300000,1.50,ml,NaN,NaN,NaN,0.87000,...,2022-10-13T01:44:58.871Z,"42 km WSW of Manley Hot Springs, Alaska",earthquake,NaN,0.300000,NaN,NaN,automatic,ak,ak

In [16]:
# check if there is any null values in columns
df.isnull().sum()

time                  0
latitude              0
longitude             0
depth                 0
mag                   1
magType               1
nst                1488
gap                1488
dmin               3479
rms                   0
net                   0
id                    0
updated               0
place                 0
type                  0
horizontalError    2473
depthError            1
magError           1785
magNst             1496
status                0
locationSource        0
magSource             0
dtype: int64

In [17]:
df.fillna(0, inplace=True)

In [18]:
df = df.loc[(df['mag'] >= 4)]

In [19]:

df['year'] = df['time'].astype(str).str[:3]
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource,year
6,2022-10-13T01:20:55.624Z,-6.1237,150.4092,10.000,4.9,mb,31.0,68.0,4.582,0.88,...,"New Britain region, Papua New Guinea",earthquake,6.52,1.897,0.106,28.0,reviewed,us,us,202
21,2022-10-12T23:09:22.873Z,34.5061,29.0325,31.768,4.1,mb,30.0,161.0,1.785,0.73,...,"196 km SSW of Kaş, Turkey",earthquake,7.23,5.434,0.102,26.0,reviewed,us,us,202
32,2022-10-12T22:44:54.465Z,38.8340,16.6971,33.741,4.3,mb,64.0,56.0,0.348,1.06,...,"5 km ESE of Barone, Italy",earthquake,4.30,2.625,0.096,31.0,reviewed,us,us,202
94,2022-10-12T17:00:09.584Z,-8.8751,126.6963,21.770,4.5,mb,26.0,59.0,2.552,0.57,...,"36 km E of Viqueque, Timor Leste",earthquake,7.85,4.702,0.128,18.0,reviewed,us,us,202
111,2022-10-12T15:09:58.328Z,-30.7799,-71.4288,59.227,4.7,mb,45.0,58.0,0.207,0.43,...,"29 km SW of Ovalle, Chile",earthquake,5.45,5.359,0.104,30.0,reviewed,us,us,202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10317,2022-09-13T03:16:47.638Z,-6.1671,146.8209,79.225,4.2,mb,12.0,106.0,3.234,0.37,...,"64 km NNW of Lae, Papua New Guinea",earthquake,12.63,7.695,0.186,8.0,reviewed,us,us,202
10321,2022-09-13T02:57:24.821Z,29.2511,138.7957,449.435,4.1,mb,27.0,81.0,3.682,0.63,...,"Izu Islands, Japan region",earthquake,9.31,10.227,0.158,11.0,reviewed,us,us,202
10325,2022-09-13T02:50:14.382Z,45.5931,26.3131,154.389,4.2,mb,30.0,39.0,0.278,0.46,...,"12 km NNE of Cașoca, Romania",earthquake,6.58,4.822,0.175,9.0,reviewed,us,us,202
10330,2022-09-13T02:43:00.144Z,-2.3839,138.1893,35.000,4.2,mb,22.0,101.0,5.958,0.76,...,"269 km ESE of Biak, Indonesia",earthquake,12.90,1.916,0.166,10.0,reviewed,us,us,202
10333,2022-09-13T02:15:34.856Z,-58.6065,-15.9633,10.000,4.6,mb,17.0,101.0,14.171,0.87,...,east of the South Sandwich Islands,earthquake,13.63,1.901,0.152,13.0,reviewed,us,us,202

In [6]:
df_to_csv = df.to_csv(r"C:\Users\Nadia\Desktop\UNI\3179\current sem\Assignment 2\Natural Disasters Datasets\cleaned\earthquake_dataset_cleaned.csv", index = False)